// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the Microflows for the MyFirstModule module

	public static boolean iVK_EntityTest_Show(IContext context, myfirstmodule.proxies.EntityTest _entityTest)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("EntityTest", _entityTest == null ? null : _entityTest.getMendixObject());
			return (Boolean)Core.execute(context, "MyFirstModule.IVK_EntityTest_Show", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static myfirstmodule.proxies.Message showMessage(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MyFirstModule.ShowMessage", params);
			return result == null ? null : myfirstmodule.proxies.Message.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}